public with sharing class CustomerInfoDetailControllerCC {

   // @AuraEnabled
   // public static List<Customer_Info_External_c__x> loadDetail() {
        //return [SELECT ExternalId FROM Customer_Info_External_c__x LIMIT 50];
    //    return [SELECT Id, contact__c, ExternalId, RecordType__c FROM Customer_Info_External_c__x WHERE contact__r.Id = '0030v000002bWbz'];
    //}
    
    //@AuraEnabled
   // public static Customer_Info_External_c__x findById(String customerInfoId) {
   //     return [SELECT RecordType__c, ExternalId
    //            FROM Customer_Info_External_c__x 
   //             WHERE Id = :customerInfoId];
    //}
}