/**
 *  @author Ivan Yeung, Venkata 
 *  @date 07/20/2017
 *  @group Test
 *  @description  Test class for OfferDefinitionLibraryService
 */

@IsTest
private class OfferDefinitionLibraryDTOTest{
    static testMethod void OfferDefinitionLibDTOTest() {
        OfferDefinitionLibraryDTO offDefDTO = new OfferDefinitionLibraryDTO();
        OfferDefinitionLibraryDTO.OfferDefinition odDTO = new OfferDefinitionLibraryDTO.OfferDefinition();
        
    }
}